'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PA_7_W_Weinert.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;h1&gt;Copyrights&lt;/h1&gt;
        '''&lt;ul&gt;
        '''&lt;li&gt;&lt;a href=&quot;https://en.wikipedia.org/wiki/Chess_piece&quot;&gt;Chess pieces&lt;/a&gt;, Copyright &lt;a href=&quot;https://en.wikipedia.org/wiki/User:Cburnett&quot;&gt;Colin M.L. Burnett&lt;/a&gt; under GFDL &amp;amp; BSD &amp;amp; GPL&lt;/li&gt;
        '''&lt;li&gt;&lt;a href=&quot;https://commons.wikimedia.org/wiki/File:Puffin_Latrabjarg_Iceland.jpg&quot;&gt;Atlantic Puffin&lt;/a&gt;, Copyright Henrik Thorburn under CC BY 3.0&lt;/li&gt;
        '''&lt;li&gt;&lt;a href=&quot;https://commons.wikimedia.org/wiki/File:Antarctic,_gentoo_penguin_%28js%29_16.jpg&quot;&gt;Gentoo Penguin&lt;/a&gt;, Copyright Jerzy St [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property about() As String
            Get
                Return ResourceManager.GetString("about", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property birds_flamingo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("birds_flamingo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property birds_owl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("birds_owl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property birds_penguin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("birds_penguin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property birds_puffin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("birds_puffin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property birds_toucan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("birds_toucan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bishop_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bishop_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bishop_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bishop_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property clock_render() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clock_render", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cloth_and_cup_render() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cloth_and_cup_render", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cup_render() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cup_render", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dahlia__Moonfire__006_flower() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dahlia__Moonfire__006_flower", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hs_2006_10_a_large_web() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hs_2006_10_a_large_web", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property king_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("king_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property king_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("king_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property knight_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("knight_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property knight_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("knight_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property line_segments_no__1_by_dazzling_rust_d4ajcpm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("line_segments_no__1_by_dazzling_rust_d4ajcpm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pawn_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pawn_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pawn_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pawn_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property queen_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("queen_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property queen_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("queen_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rook_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rook_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rook_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rook_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rosa__moonlight__Moschatahybride_002_flower() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rosa__moonlight__Moschatahybride_002_flower", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wood_cup_render() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wood_cup_render", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
